### ISSUE TITLE
Formatting Codebase

### ISSUE THREAD

**Issue by tombrain** [henshingly/lmo_php8#11]
Hallo @henshingly,

hast du dir schon mal Gedanken darüber gemacht, ob du nicht die komplette Codebase mal durch einen Code-Formatter jagen willst?

Damit wäre der Code doch wesentliche leichter zu warten.

**Comment by henshingly** [comment]
Was für Erfahrungen hast Du denn mit solchen Tools? 
Kenne nur DupliChecker
Welchen würdest Du denn präferieren?

Schönen Sonntag noch 
Gruß

**Comment by tombrain** [comment]
Ich entwickle mit VSCode und nutze das PlugIn von https://intelephense.com/

Um alle Dateien auf einmal zu konvertieren, nutze ich ein weiteres PlugIn.

Ich könnte auch mal alles umstellen und dafür ein Merge-Request machen.

**Comment by henshingly** [comment]
Ich habe den LMO bisher immer in einem  Editor (notepad++) bearbeitet. Und das auch schon seit 2003.
Natürlich weiß mannach so langerZeit wo die Stellschrauben sind. Hatte mir bisher immer gereicht.
Ob ich nach einem Formatter Durchlauf noch den Code lesen kann, weiß ich nicht. Die VSCode-Umgebung müsste ich noch einrichten.
Habe momentan aber wenig Zeit, denn ich bin grade dabei mein Equipment für den kommenden Tauchurlaub vorzubereiten.
Habe auf der Arbeit auch wenig Zeit (hoher Krankenstand) und viel zu tun.
Vielleicht kannst Du ja mal einen Durchlauf starten und mir mal das Ergebnis schicken, würde ich mir gerne ansehen. 

MfG Henshingly
