### ISSUE TITLE
Warning: Undefined array key

### ISSUE THREAD

**Issue by henshingly** [henshingly/lmo_php8#14]
When using the second half of the season hack, the message Warning: Undefined array key 9 in /lmo/addon/classlib/classes/liga.class.php on line 749 is output 34 times in a league with 34 match days.

The line contains the following code
`} while (is_object($spieltag->partien[++$pCounter]) && $partienCounter < $spieltag->getModus() );`

**Comment by webfalter** [comment]
https://github.com/henshingly/lmo_php8/blob/a1d0238131485e3b6f246640751bd9df2163bc36/lmo/lmo-rueckrunde.php#L39C69-L39C100
$partie = new Partie($p->spNr, NULL, NULL, $p->gast, $p->heim, -1, -1, NULL, NULL);

**Comment by henshingly** [comment]
I have now tried all possible variants
`$partie = new Partie($p->spNr, NULL, NULL, $p->gast, $p->heim, -1, -1, NULL, '');`
`$partie = new Partie($p->spNr, NULL, NULL, $p->gast, $p->heim, -1, -1, NULL, 'NULL;`
`$partie = new Partie($p->spNr, NULL, NULL, $p->gast, $p->heim, -1, -1, '', '');`
`$partie = new Partie($p->spNr, NULL, NULL, $p->gast, $p->heim, -1, -1, NULL, "");`
`$partie = new Partie($p->spNr, NULL, NULL, $p->gast, $p->heim, -1, -1, "", "");`

Always with the same result
`Warning: Undefined array key 9 in D:\xweb\htdocs\lmo\addon\classlib\classes\liga.class.php on line 749
The second half of the season schedule has been successfully saved.`

**Comment by henshingly** [comment]
With webfalter's suggested solution, the PHP warnings are intercepted
change
`
            if ( $pCounter > 10000 ) {
              die("Script Fehler");
            }
          } while (is_object($spieltag->partien[++$pCounter]) && $partienCounter < $spieltag->getModus() );`
against
`
            if($pCounter > 10000 ) die("Script ERROR");                       
            ++$pCounter; // NEW 2012-06-27 Timme
          } while (isset($spieltag->partien[$pCounter]) && is_object($spieltag->partien[$pCounter]) && $partienCounter < $spieltag->getModus() );`


Thanks webfalter
