### ISSUE TITLE
New format for UEFA club competitions

### ISSUE THREAD

**Issue by henshingly** [henshingly/lmo_php8#15]
Mit den [Änderungen von dwblmo](https://github.com/dwblmo/LMO_PHP8/commit/8b49238ff56474e06aec130df611e89ae1007d29) zur Anpassung des LMO's für die Erstellung eines UEFA-Klubwettbewerbs habe ich , [nach der Anpassung in diesem LMO](https://github.com/henshingly/lmo_php8/commit/aa0824a9142cb2bb510f373cd3fefd72b299a779), jede Menge PHP-Warnungen.
Beim Erstellen eines KO-Turniers mit 24 Mannschaften, den Spielmodus Einzelspiel bei allen 5 Runden, bekomme ich einen error_log mit [133 Zeilen PHP Warning](https://github.com/user-attachments/files/16992855/php_error_log.txt).
Wenn ich bei den Runden 1-4 Hin- und Rückspiel auswähle sind es sogar [221 Zeilen Warnungen](https://github.com/user-attachments/files/16992884/php_error_log_Hin_und_Rueckspiel.txt).

With the [changes from dwblmo](https://github.com/dwblmo/LMO_PHP8/commit/8b49238ff56474e06aec130df611e89ae1007d29) to adapt the LMO for the creation of a UEFA club competition, I have after the [adaptation](https://github.com/henshingly/lmo_php8/commit/aa0824a9142cb2bb510f373cd3fefd72b299a779)  in this LMO lots of PHP warnings.
When creating a knockout tournament with 24 teams, the game mode single game for all 5 rounds, I get an error_log with [133 lines PHP Warnings](https://github.com/user-attachments/files/16992855/php_error_log.txt) .
If I select the return leg in rounds 1-4 there are even [221 lines of warnings](https://github.com/user-attachments/files/16992884/php_error_log_Hin_und_Rueckspiel.txt).

**Comment by babbisch** [comment]
fixed https://github.com/dwblmo/LMO_PHP8/commit/f76616cd58654d5e6665a5f5608526e5751b0f8f

**Comment by henshingly** [comment]
fixed 0f21cf6fcbab9d719d24a389094a4b7e9151d07c

Thanks DwB
