### ISSUE TITLE
Stats without template

### ISSUE THREAD

**Issue by henshingly** [henshingly/lmo_php8#19]
When the league statistics are called up, the template is not [loaded](https://vest-sport.de/lmo_git/lmo.php?file=1l_2021-22.l98&action=stats&stat1=0&stat2=0)
[Sample league](https://vest-sport.de/lmo_git/lmo.php?file=1l_2021-22.l98)

**Comment by babbisch** [comment]
Das hier hast Du ja geändert: https://github.com/henshingly/lmo_php8/blob/master/lmo/lmo-showstats.php#L324-L329

In der aufrufenden lmo-zustat.php wird als erste geprüft, ob Admin-Rechte vorhanden sind (die lmo-zustat.php wird im Original nur in der [lmo-savefile.php](https://github.com/henshingly/lmo_php8/blob/master/lmo/lmo-savefile.php#L30) und [lmo-updateaddons.php](https://github.com/henshingly/lmo_php8/blob/master/lmo/addon/classlib/update_addons.php#L41) aufgeruden, also aus der Administration heraus.

[require_once](https://github.com/henshingly/lmo_php8/blob/master/lmo/lmo-zustat.php#L21) rausnehmen

**Comment by henshingly** [comment]
fixed bfc8cb9f449d531643e30e64c5c1f8f3cfcf7bac
ich habe mich schon totgesucht und den Wald vor lauter Bäumen nicht gesehen

THX @babbisch

**Comment by babbisch** [comment]
sehe auch gerade, dass ich da noch einen Uralt-Zustand bei mir habe. joker hat das ja schon vor mehr als einem Jahrzehnt korrigiert und die lmo-zustat.php direkt eingebunden. Halte ich für Overkill, jedes Mal die Dateien zu erzeugen, die Statistik ändert sich ja erst mit neuen Ergebnissen und dann reicht der Aufruf beim speichern, aber der Code wird halt weniger.
