### ISSUE TITLE
Frage zu Emails mittels PHPMailer

### ISSUE THREAD

**Issue by tombrain** [henshingly/lmo_php8#22]
Hallo @henshingly ,

mit folgendem Checkin hast du auf PHPMailer umgestellt: https://github.com/henshingly/lmo_php8/commit/2b822b3676e7d1d2090795b60ca16edf7dd09e81

Funktioniert das bei dir? Laut Doku von PHPMailer muss man eigentlich Daten eines Email-Accounts angeben, damit man damit Emails versenden kann.

[https://github.com/PHPMailer/PHPMailer](https://github.com/PHPMailer/PHPMailer)
```
$mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
    $mail->isSMTP();                                            //Send using SMTP
    $mail->Host       = 'smtp.example.com';                     //Set the SMTP server to send through
    $mail->SMTPAuth   = true;                                   //Enable SMTP authentication
    $mail->Username   = 'user@example.com';                     //SMTP username
    $mail->Password   = 'secret';                               //SMTP password
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;            //Enable implicit TLS encryption
    $mail->Port       = 465;                                    //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`

```

Ich habe es jetzt mal mit Ligen-Download und Emails an Tipper zu versenden versucht. Beides klappt bei mir aktuell nicht.

**Comment by babbisch** [comment]
Das ist nur notwendig, wenn Du mit SMTP senden möchtest. Es ght auch ohne, siehe https://github.com/PHPMailer/PHPMailer/blob/master/examples/mail.phps

**Comment by henshingly** [comment]
Also grade noch mal getestet

In den Admineinstellungen die email Adresse hinterlegt
![adminmail](https://github.com/user-attachments/assets/2395ddcf-3613-4686-9eac-a5a943950a8c)
Dann habe ich an web.de, gmail.com, gmx.de, vest-sport.de und yahoo.de Ligen versendet. Bis auf yahoo.de kamen alle Ligen bei den entsprechenden Empfängern an.
Dann 6 Testtipper angelegt (mit 2 x vest-sport.de, gmail.com, web.de, gmx.de und yahoo.de) Newsletter an Alle
![news](https://github.com/user-attachments/assets/4f64ce2d-6c15-4a80-b66f-c72df2cacd82)
 und Tipp-Reminder versendet.
![reminder](https://github.com/user-attachments/assets/8255a986-8f50-4db0-9927-9dda2ba89b11)
 Bis auf yahoo.de kamen wieder alle an.
![mail](https://github.com/user-attachments/assets/b99cc4e3-0176-4a7b-8a9f-b91abe07879d)

Habe momentan noch keine Idee warum yahoo mal wieder Zicken macht.

Gruß Henshingly

**Comment by babbisch** [comment]
Stackoverflow: https://stackoverflow.com/questions/19555650/php-mail-vs-yahoo-can-someone-simply-explain-steps-required-for-yahoo-to-rece
11 Jahre alt...

Yahoo scheint Mails versendet mit `mail()` nicht zu akzeptieren, hier ist, siehe 1. Antwort, SMTP notwendig. Yahoo scheint hier eine Ausnahme zu sein.

Was halt wieder nervig dabei ist: Passwort für SMTP-Zugang im Klartext.

**Comment by babbisch** [comment]
Folgendes ergänzen (bzw. erste Zeile austauschen für `$mail->isMail();` und ggf. mit den Ports spielen (465 für TLS, 587 für STARTTLS. Im äußersten Notfall Port 25 nehmen)

```
$mail->isSMTP();
$mail->Host = 'smtp.example.com';
$mail->Port = 587;
$mail->SMTPAuth = true;
$mail->Username = 'sender@example.com';
$mail->Password = 'myUnhackablePassword';
```

Habe kleine Yahoo-Adresse zum testen

**Comment by tombrain** [comment]
> Das ist nur notwendig, wenn Du mit SMTP senden möchtest. Es ght auch ohne, siehe https://github.com/PHPMailer/PHPMailer/blob/master/examples/mail.phps

ich hab jetzt mal auf meinem Provider den Beispielcode getestet. Offensichtlich lässt mein Provider (1und1) das `sendmail` nicht mehr zu.

das erscheint bei mir:

`Mailer Error: Could not instantiate mail function.`

Ich glaube auch dass googlemail das mittlerweile nicht mehr zulässt...

**Comment by babbisch** [comment]
Hast du es mit dem obigen Beispiel für SMTP und deinen Credentials versucht?

**Comment by tombrain** [comment]
> Hast du es mit dem obigen Beispiel für SMTP und deinen Credentials versucht?

so klappts:

![image](https://github.com/user-attachments/assets/1637e804-3a39-4aba-bc4e-209611e46a76)

**Comment by babbisch** [comment]
Das blöde hierbei ist, wenn man es in den Standard aufnimmt, die Zugangsdaten in die cfg.txt aufzunehmen sind. Und das halt im Klartext.

Eröffnet halt unschöne Nebenwirkungen. In deinem Fall wohl alternativlos außer du sendest von einem Mailprovider, der nicht zwingend SMTP vorschreibt.

**Comment by tombrain** [comment]
ich hab jetzt meinen Fehler gefunden. Ich hatte bei meinem Test-LMO die Absender-Email nicht angepasst. Jetzt funktioniert es auch bei mir.

**Comment by henshingly** [comment]
Manchmal frage ich mich warum ich mir die Mühe mit den Fotostorys mache. 🤪

Was machen denn eigentlich deine Commits genau?  Haben die bei Dir die richtigen Fehler gemeldet? 

Gruß Henshingly
