### ISSUE TITLE
Tippspiel: Notizen zur Partie zerlegt Layout

### ISSUE THREAD

**Issue by FireFlyer47** [henshingly/lmo_php8#7]
So bald ein Eintrag unter Notizen zu einer Partie hinterlegt wurde, so zerlegt es das Layout im Tippspiel. Betroffen sind der Menupunkt "Übersicht" und "Alle Spiele in den nächsten X Tagen"

Damit es gepinnt ist. Muss da mal in der Winterpause versuche starten.

**Comment by henshingly** [comment]
Das hat mit der Funktion mysql_escape_string zu tun. Diese wurde in PHP 7.0.0 entfernt (siehe [Link](http://php.net/manual/de/function.mysql-escape-string.php))
Wurde bisher zum maskieren eines Strings benutzt. War mir schon vor ein paar Monaten aufgefallen. Habe dafür aber noch keine Lösung. Die Funktion kommt im LMO noch ein paarmal an anderen Stellen vor. 
Jedesmal wenn irgenwo ein Mausover erscheinen soll.
MfG Dietmar

**Comment by henshingly** [comment]
Habe in 10 Dateien nach einiger Suche eine passende PHP Funktion statt der mysql_escape_string() reingeschrieben.
Habe in der tipp/lmo-tippviewer.php außerdem noch einen kleinen Fehler der mit PHP7 auftauchte behoben. Es kam nämlich eine Notice. Das ein Mannschaftsname ein undefinierter Index wäre.
Probiere mal aus indem Du dir die Zip Datei neu downloadest.
:-)

**Comment by FireFlyer47** [comment]
Ich fahr heut nach der Arbeit gleich in Urlaub. Werde es mir danach anschauen. Musste diese Woche leider auch noch neuen PC installieren, da mein alter komplett abgeraucht ist. Cool, dass du weiter so aktiv bist. Weihnachtsbastelei erfolgreich beendet?

**Comment by henshingly** [comment]
Hatte die letzten Tage einen Krankenschein. Habe mir in den Finger gefräst:-)

MfG Dietmar

________________________________

**Comment by FireFlyer47** [comment]
Hab die Dateien bei mir ersetzt. Sehr gute Arbeit, läuft alles sauber.
Ein gutes Neues dir noch!
